### ISSUE TITLE
having mods .jar files technically counts as mod reposting

### ISSUE THREAD

**Issue by ROMVoid95** [SebaSphere/GalacticScience#1]
just wanted to point this out :)

**Comment by SebaSphere** [comment]
Well yeah but should be fine. Basically every modpack ever technically is jar reposting lmao.

**Comment by ROMVoid95** [comment]
not when there hosted on curseforge bruh

**Comment by SebaSphere** [comment]
True. Either way, I don't think mod devs would have a issue with working on the pack on github. Gonna close the issue.
